### ISSUE TITLE
Where to get the SDK

### ISSUE THREAD

**Issue by alexeygolev** [100askTeam/100ask_r128_demos#1]
Thank you for creating this set of demos. Unfortunately it's not clear where one gets the R128 SDK. I asked on aw-ol.com but the response was "the SDK is not ready". But then I can see projects like yours and it confuses me as your instructions reference the SDK.

I assume I'm looking at the wrong place. Please assist

**Comment by YobieZhou** [comment]
Hi, I will send you the SDK, please leave your email

**Comment by alexeygolev** [comment]
@YobeZhou Thank you. My email is vaavgolevs@gmail.com
